# Uncomment once rubocop-rspec 1.0 is released...
# require: rubocop-rspec

Documentation:
  Enabled: false

DotPosition:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Max: 15

AllCops:
  Include:
    - Guardfile
    - '**/Rakefile'
    - pacto*.gemspec
  Exclude:
    - bin/**/*
    - tmp/**/*
